---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewStarterRugProject"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "7557a1b6213caa4ea8d4ae71785722339bcc75a3"
    sha: "7557a1b"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.3"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "738735a"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.3"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "738735a"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.3"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "738735a"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.5"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "caa346c"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.5"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "caa346c"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.5"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "caa346c"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.9"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "restrict-cors"
    sha: "e241a51"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.9"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "restrict-cors"
    sha: "e241a51"
  parameters:
    - "component": "patch"

